#!/usr/bin/env python3
"""Generates visual traceability views from the Requirements-as-Code records.

Two outputs, both from the same graph:

  07_verification/reports/traceability_views.md    scoped Mermaid graphs, rendered by GitHub
  07_verification/reports/trace_explorer.html      self-contained interactive explorer

Reuses the front-matter parser of tools/trace_check.py -- standard library only, no
third-party dependency.

Usage:
    python3 tools/gen_trace_graph.py             # write/update both outputs
    python3 tools/gen_trace_graph.py --check     # check only, exit 1 if stale
    python3 tools/gen_trace_graph.py --root DIR  # different repo root

Exit 0 = up to date or written, 1 = stale (with --check only), 2 = error.

NOTE: produces views used to understand and review the safety case and is therefore --
like trace_check.py and gen_index.py -- a candidate for tool qualification
(ISO 26262-8, Clause 11). See 09_process/plans/tool_qualification.md.
The HTML explorer additionally puts JavaScript between the record and its presentation;
the Mermaid views do not.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_check import load_records, ID_PATTERN  # noqa: E402

MARKER = "<!-- generated by tools/gen_trace_graph.py -- do not edit manually -->"

# Order of the levels, used for layout and for the legend.
LEVEL = {
    "H": 0, "CR": 0,
    "SG": 1,
    "FSR": 2,
    "TSR": 3,
    "SYS-REQ": 3,
    "HW-REQ": 4, "SW-REQ": 4, "SM": 4,
    "TC": 5,
    "RISK": 6, "A": 6,
}

COLOR = {
    "H":       ("#fdf0e3", "#c07d29"),
    "CR":      ("#e7f0fb", "#3b6ea5"),
    "SG":      ("#fbeaea", "#b05252"),
    "FSR":     ("#fbeaea", "#b05252"),
    "TSR":     ("#f0edf7", "#7a5ea8"),
    "SYS-REQ": ("#e7f0fb", "#3b6ea5"),
    "HW-REQ":  ("#eaf4ea", "#4a8a4a"),
    "SW-REQ":  ("#eaf4ea", "#4a8a4a"),
    "SM":      ("#eaf4ea", "#4a8a4a"),
    "TC":      ("#fdf0e3", "#c07d29"),
    "RISK":    ("#f2f2f4", "#9a9aa5"),
}


def kind(rid: str) -> str:
    return rid.rsplit("-", 1)[0]


def node_id(rid: str) -> str:
    """Mermaid node ids must not contain hyphens."""
    return rid.replace("-", "_")


def build_graph(records: dict) -> tuple[list, dict, dict]:
    """Returns (edges, downstream, upstream). Edge = (parent, child, relation)."""
    edges: list[tuple[str, str, str]] = []
    for rid, rec in records.items():
        for parent in rec["derived_from"]:
            if parent in records:
                edges.append((parent, rid, "derived_from"))
        for target in rec["allocated_to"]:
            if ID_PATTERN.match(target) and target in records:
                edges.append((rid, target, "allocated_to"))
        for tc in rec["verified_by"]:
            if tc in records:
                edges.append((rid, tc, "verified_by"))

    downstream: dict[str, list] = {}
    upstream: dict[str, list] = {}
    for a, b, rel in edges:
        downstream.setdefault(a, []).append((b, rel))
        upstream.setdefault(b, []).append((a, rel))
    return edges, downstream, upstream


def reachable(start: str, downstream: dict, upstream: dict) -> set[str]:
    """All records connected to `start`, downstream and upstream."""
    seen = {start}
    stack = [start]
    while stack:
        n = stack.pop()
        for nxt, _ in downstream.get(n, []) + upstream.get(n, []):
            if nxt not in seen:
                seen.add(nxt)
                stack.append(nxt)
    return seen


# ----------------------------------------------------------------- Mermaid views


def mermaid(scope: set[str], records: dict, edges: list, title: str,
            relations: tuple = ("derived_from", "allocated_to", "verified_by")) -> str:
    """One Mermaid flowchart for the given set of record ids.

    `relations` limits which link kinds are drawn. Large views draw the derivation skeleton
    only - allocation and verification links converge on few nodes and turn the graph into a
    hairball. They remain complete in the link table under every view.
    """
    nodes = sorted(scope, key=lambda r: (LEVEL.get(kind(r), 9), r))
    lines = ["```mermaid", "flowchart LR"]

    for rid in nodes:
        rec = records[rid]
        asil = str(rec.get("asil", "")).strip()
        badge = f"<br/><small>ASIL {asil}</small>" if asil and asil != "-" else ""
        status = str(rec.get("status", "")).strip()
        st = f"<br/><small>{status}</small>" if status else ""
        lines.append(f'    {node_id(rid)}["<b>{rid}</b>{badge}{st}"]')

    for a, b, rel in sorted(edges):
        if a in scope and b in scope and rel in relations:
            if rel == "derived_from":
                lines.append(f"    {node_id(a)} --> {node_id(b)}")
            elif rel == "verified_by":
                lines.append(f'    {node_id(a)} -.->|"verified_by"| {node_id(b)}')
            else:
                lines.append(f'    {node_id(a)} -.->|"allocated_to"| {node_id(b)}')

    by_kind: dict[str, list] = {}
    for rid in nodes:
        by_kind.setdefault(kind(rid), []).append(node_id(rid))
    for k, ids in sorted(by_kind.items()):
        fill, stroke = COLOR.get(k, ("#ffffff", "#888888"))
        cls = k.replace("-", "_").lower()
        lines.append(f"    classDef {cls} fill:{fill},stroke:{stroke},color:#1a1a1a")
        lines.append(f"    class {','.join(ids)} {cls}")

    # Click targets. GitHub may ignore click directives depending on its Mermaid
    # security setting, which is why the link table below every view is authoritative.
    for rid in nodes:
        rel_path = records[rid]["_file"]
        lines.append(f'    click {node_id(rid)} href "../../{rel_path}" "{rid}"')

    lines.append("```")
    return "\n".join(lines)


def link_table(scope: set[str], records: dict, upstream: dict, downstream: dict) -> str:
    rows = ["| Record | ASIL | Status | Upstream | Downstream |", "|---|---|---|---|---|"]
    for rid in sorted(scope, key=lambda r: (LEVEL.get(kind(r), 9), r)):
        rec = records[rid]
        up = ", ".join(sorted(a for a, _ in upstream.get(rid, []))) or "—"
        dn = ", ".join(sorted(b for b, _ in downstream.get(rid, []))) or "—"
        rows.append(
            f"| [{rid}](../../{rec['_file']}) | {rec.get('asil','—')} | "
            f"{rec.get('status','—')} | {up} | {dn} |"
        )
    return "\n".join(rows)


GOLDEN_THREAD = ["H-01", "H-04", "CR-007", "SG-01", "FSR-001", "TSR-003",
                 "SYS-REQ-014", "SYS-REQ-018", "SM-01", "TC-021"]


def build_views(records: dict, edges: list, downstream: dict, upstream: dict) -> str:
    out = [
        "# Traceability views",
        "",
        MARKER,
        "",
        "Visual companion to the traceability matrix. The matrix proves completeness; these views",
        "show the paths. Both come from the same records — edit the record, never this file.",
        "",
        "**Reading the graphs:** solid arrows are derivation (`derived_from`), dotted arrows are",
        "allocation and verification. Colour encodes the record kind, the badge the ASIL and the",
        "status. Node clicks may or may not work depending on the Mermaid settings of the viewer —",
        "the link table under each view always works.",
        "",
    ]

    # 1) Golden Thread
    gt = {r for r in GOLDEN_THREAD if r in records}
    if gt:
        out += ["## 1 Golden Thread — SG-01", "",
                "The one chain worked out in full depth, from the hazard to the test case.", "",
                mermaid(gt, records, edges, "Golden Thread"), "",
                link_table(gt, records, upstream, downstream), ""]

    # 2) One view per safety goal
    sgs = sorted(r for r in records if kind(r) == "SG")
    for n, sg in enumerate(sgs, start=2):
        scope = reachable(sg, downstream, upstream)
        # Keep the view readable: drop customer requirements from the large safety goal views,
        # they are covered by the per-safety-goal table and by the folder overviews.
        large = len(scope) > 25
        rels = ("derived_from",) if large else (
            "derived_from", "allocated_to", "verified_by")
        trimmed = {r for r in scope if kind(r) != "CR"} if large else set(scope)
        if large:
            # Drop nodes that lost every link when the customer requirements were removed -
            # an isolated box carries no information.
            linked = {a for a, b, r in edges if r in rels and a in trimmed and b in trimmed}
            linked |= {b for a, b, r in edges if r in rels and a in trimmed and b in trimmed}
            trimmed &= linked
        dropped = len(scope) - len(trimmed)
        out += [f"## {n} Safety goal {sg} — full context", "",
                f"{len(scope)} connected records."]
        if large:
            out += [f"*Graph shows the derivation skeleton only ({len(trimmed)} of {len(scope)} "
                    f"records; customer requirements and isolated nodes omitted). Allocation and "
                    f"verification links converge on few nodes and would obscure the structure — "
                    f"they are complete in the table below.*"]
        out += ["", mermaid(trimmed, records, edges, sg, rels), "",
                link_table(scope, records, upstream, downstream), ""]

    # 3) Level summary
    counts: dict[str, int] = {}
    for rid in records:
        counts[kind(rid)] = counts.get(kind(rid), 0) + 1
    out += [f"## {len(sgs) + 2} Level summary", "",
            f"{len(records)} records, {len(edges)} typed links.", "",
            "| Level | Kind | Records |", "|---|---|---|"]
    for k in sorted(counts, key=lambda k: (LEVEL.get(k, 9), k)):
        out.append(f"| {LEVEL.get(k, '—')} | `{k}-` | {counts[k]} |")
    out += ["", "Interactive exploration of all records: [`trace_explorer.html`]"
                "(trace_explorer.html) — open it locally in a browser; GitHub does not render "
                "HTML files stored in a repository.", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ HTML explorer


def build_explorer(records: dict, edges: list, downstream: dict, upstream: dict) -> str:
    data = {
        "nodes": [
            {
                "id": rid,
                "kind": kind(rid),
                "asil": str(rec.get("asil", "") or ""),
                "status": str(rec.get("status", "") or ""),
                "type": str(rec.get("type", "") or ""),
                "text": " ".join(str(rec.get("text", "")).split())[:400],
                "file": rec["_file"],
                "level": LEVEL.get(kind(rid), 9),
            }
            for rid, rec in sorted(records.items())
        ],
        "edges": [{"from": a, "to": b, "rel": r} for a, b, r in sorted(edges)],
        "colors": {k: v[0] for k, v in COLOR.items()},
        "strokes": {k: v[1] for k, v in COLOR.items()},
    }
    payload = json.dumps(data, ensure_ascii=False)
    return _EXPLORER_TEMPLATE.replace("/*__DATA__*/", payload)


_EXPLORER_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Traceability explorer — lighting system</title>
<!-- generated by tools/gen_trace_graph.py -- do not edit manually -->
<style>
  :root { --bg:#ffffff; --fg:#1a2430; --muted:#6b7a8d; --line:#d8e0ea; --panel:#f7fafd; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0f1419; --fg:#e2e8ef; --muted:#95a3b4; --line:#2a3542; --panel:#161d25; }
  }
  * { box-sizing: border-box; }
  body { margin:0; font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
         background:var(--bg); color:var(--fg); }
  header { padding:14px 20px; border-bottom:1px solid var(--line); display:flex; gap:16px;
           align-items:center; flex-wrap:wrap; }
  h1 { font-size:17px; margin:0; font-weight:700; }
  .muted { color:var(--muted); font-size:13px; }
  input, select { font:inherit; padding:6px 10px; border:1px solid var(--line);
                  border-radius:7px; background:var(--bg); color:var(--fg); }
  main { display:grid; grid-template-columns:minmax(240px,320px) 1fr; height:calc(100vh - 62px); }
  #list { overflow:auto; border-right:1px solid var(--line); }
  #list div.row { padding:7px 14px; cursor:pointer; border-bottom:1px solid var(--line);
                  display:flex; gap:8px; align-items:baseline; }
  #list div.row:hover { background:var(--panel); }
  #list div.row.sel { background:var(--panel); font-weight:700; }
  .pill { font-size:11px; padding:1px 7px; border-radius:99px; border:1px solid; white-space:nowrap; }
  #detail { overflow:auto; padding:20px 24px; }
  #detail h2 { margin:0 0 4px; font-size:20px; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-top:18px; }
  .box { border:1px solid var(--line); border-radius:9px; padding:12px 14px; background:var(--panel); }
  .box h3 { margin:0 0 8px; font-size:13px; text-transform:uppercase; letter-spacing:.4px;
            color:var(--muted); }
  .box a { display:inline-block; margin:2px 6px 2px 0; text-decoration:none; color:inherit;
           border:1px solid var(--line); border-radius:6px; padding:2px 8px; background:var(--bg); }
  .box a:hover { border-color:var(--muted); }
  .rel { color:var(--muted); font-size:11px; }
  svg { width:100%; height:320px; border:1px solid var(--line); border-radius:9px;
        margin-top:18px; background:var(--panel); }
  code { background:var(--panel); padding:1px 5px; border-radius:4px; font-size:13px; }
  @media (max-width:820px){ main{grid-template-columns:1fr; height:auto} #list{max-height:40vh} }
</style></head><body>
<header>
  <h1>Traceability explorer</h1>
  <input id="q" type="search" placeholder="Search id or text…" style="min-width:220px">
  <select id="kindf"><option value="">all kinds</option></select>
  <select id="asilf"><option value="">all ASIL</option></select>
  <span class="muted" id="count"></span>
</header>
<main>
  <div id="list"></div>
  <div id="detail"><p class="muted">Select a record on the left.</p></div>
</main>
<script>
const DATA = /*__DATA__*/;
const byId = Object.fromEntries(DATA.nodes.map(n => [n.id, n]));
const down = {}, up = {};
for (const e of DATA.edges) {
  (down[e.from] = down[e.from] || []).push([e.to, e.rel]);
  (up[e.to] = up[e.to] || []).push([e.from, e.rel]);
}
const $ = s => document.querySelector(s);
let selected = null;

for (const k of [...new Set(DATA.nodes.map(n => n.kind))].sort())
  $("#kindf").insertAdjacentHTML("beforeend", `<option>${k}</option>`);
for (const a of [...new Set(DATA.nodes.map(n => n.asil).filter(Boolean))].sort())
  $("#asilf").insertAdjacentHTML("beforeend", `<option>${a}</option>`);

function pill(n) {
  const bg = DATA.colors[n.kind] || "#eee", st = DATA.strokes[n.kind] || "#888";
  return `<span class="pill" style="background:${bg};border-color:${st};color:#1a1a1a">${n.kind}</span>`;
}

function renderList() {
  const q = $("#q").value.toLowerCase(), k = $("#kindf").value, a = $("#asilf").value;
  const rows = DATA.nodes.filter(n =>
    (!k || n.kind === k) && (!a || n.asil === a) &&
    (!q || n.id.toLowerCase().includes(q) || n.text.toLowerCase().includes(q)));
  $("#count").textContent = `${rows.length} of ${DATA.nodes.length} records`;
  $("#list").innerHTML = rows.map(n =>
    `<div class="row${n.id === selected ? " sel" : ""}" data-id="${n.id}">${pill(n)}
     <span>${n.id}</span><span class="muted" style="margin-left:auto">${n.asil}</span></div>`).join("");
  for (const el of document.querySelectorAll("#list .row"))
    el.onclick = () => select(el.dataset.id);
}

function links(list) {
  if (!list || !list.length) return '<span class="muted">none</span>';
  return list.map(([id, rel]) =>
    `<a href="#" data-id="${id}">${id} <span class="rel">${rel}</span></a>`).join("");
}

function graph(id) {
  const nodes = [[id, 0]];
  for (const [n] of (up[id] || [])) nodes.push([n, -1]);
  for (const [n] of (down[id] || [])) nodes.push([n, 1]);
  const cols = {"-1": [], "0": [], "1": []};
  for (const [n, c] of nodes) cols[c].push(n);
  const W = 900, H = 300, colX = {"-1": 120, "0": W / 2, "1": W - 120};
  let out = `<svg viewBox="0 0 ${W} ${H}">`;
  const pos = {};
  for (const c of ["-1", "0", "1"]) {
    const arr = cols[c], step = H / (arr.length + 1);
    arr.forEach((n, i) => pos[n] = [colX[c], step * (i + 1)]);
  }
  for (const [n] of (up[id] || []))
    out += `<line x1="${pos[n][0] + 55}" y1="${pos[n][1]}" x2="${pos[id][0] - 55}" y2="${pos[id][1]}"
            stroke="#8FA3BA" stroke-width="1.5" marker-end="url(#a)"/>`;
  for (const [n] of (down[id] || []))
    out += `<line x1="${pos[id][0] + 55}" y1="${pos[id][1]}" x2="${pos[n][0] - 55}" y2="${pos[n][1]}"
            stroke="#8FA3BA" stroke-width="1.5" marker-end="url(#a)"/>`;
  for (const n in pos) {
    const nd = byId[n], bg = DATA.colors[nd.kind] || "#eee", st = DATA.strokes[nd.kind] || "#888";
    out += `<g><rect x="${pos[n][0] - 55}" y="${pos[n][1] - 16}" width="110" height="32" rx="7"
            fill="${bg}" stroke="${st}" stroke-width="${n === id ? 2.5 : 1.5}"/>
            <text x="${pos[n][0]}" y="${pos[n][1] + 5}" text-anchor="middle" font-size="13"
            fill="#1a1a1a" font-weight="${n === id ? 700 : 400}">${n}</text></g>`;
  }
  out += `<defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6"
          markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#8FA3BA"/></marker></defs></svg>`;
  return out;
}

function select(id) {
  selected = id;
  const n = byId[id];
  $("#detail").innerHTML = `
    <h2>${pill(n)} ${n.id}</h2>
    <p class="muted">${n.type} · ASIL ${n.asil || "—"} · status ${n.status || "—"} ·
       <code>${n.file}</code></p>
    <p>${n.text || ""}</p>
    ${graph(id)}
    <div class="grid">
      <div class="box"><h3>Upstream — derives from</h3>${links(up[id])}</div>
      <div class="box"><h3>Downstream — feeds</h3>${links(down[id])}</div>
    </div>`;
  for (const el of document.querySelectorAll("#detail a[data-id]"))
    el.onclick = e => { e.preventDefault(); select(el.dataset.id); renderList(); };
  renderList();
}

for (const el of ["#q", "#kindf", "#asilf"]) $(el).oninput = renderList;
renderList();
</script></body></html>
"""


# ------------------------------------------------------------------------ driver


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".", help="repo root (default: .)")
    ap.add_argument("--check", action="store_true", help="check only, write nothing")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: root not found: {root}", file=sys.stderr)
        return 2

    records, _ = load_records(root)
    if not records:
        print("No records found - nothing to do.")
        return 0

    edges, downstream, upstream = build_graph(records)
    outputs = {
        root / "07_verification/reports/traceability_views.md":
            build_views(records, edges, downstream, upstream),
        root / "07_verification/reports/trace_explorer.html":
            build_explorer(records, edges, downstream, upstream),
    }

    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale traceability views:")
            for s in stale:
                print(f"  - {s}")
            print("\nPlease run 'python3 tools/gen_trace_graph.py' and commit the result.")
            return 1
        print(f"Traceability views up to date ({len(records)} records, {len(edges)} links).")
        return 0

    print(f"Traceability views written: {len(records)} records, {len(edges)} links.")
    for path in outputs:
        print(f"  - {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
