#!/usr/bin/env python3
"""Generates a README.md overview for every folder holding Requirements-as-Code records.

Any folder containing at least one Markdown file with YAML front matter and an `id` field gets a
generated README.md with a clickable table of all its records. GitHub renders that file
automatically when the folder is opened.

Uses the same front-matter parser as tools/trace_check.py -- no third-party dependency.

Usage:
    python3 tools/gen_index.py             # write/update the overviews
    python3 tools/gen_index.py --check     # check only, exit 1 if stale
    python3 tools/gen_index.py --root DIR  # different repo root

Exit 0 = up to date or written, 1 = stale (with --check only), 2 = error.

NOTE: produces overviews used for the safety case and is therefore -- like trace_check.py --
a candidate for tool qualification (ISO 26262-8, Clause 11).
See 09_process/plans/tool_qualification.md.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_check import parse_front_matter, LIST_FIELDS  # noqa: E402

MARKER = "<!-- generated by tools/gen_index.py -- do not edit manually -->"

# Above this many records in one folder, the generator suggests a split - together with the
# evidence needed to decide it. The rule: split only by a field that is single-valued for
# EVERY record in the folder. `allocated_to` is many-to-many for hardware requirements, so a
# split by component would force an arbitrary filing decision per record.
SPLIT_THRESHOLD = 40

# Grouped sections are only worth printing when they actually group something.
GROUP_MIN_RECORDS = 5
GROUP_MIN_BUCKETS = 2
# A grouping that puts almost everything into one bucket does not group anything - it only
# adds noise. Suppress it when the largest bucket holds this share or more.
GROUP_MAX_DOMINANCE = 0.8

SKIP_DIRS = {".git", ".github", ".claude", "node_modules", "__pycache__", "exports"}

# Heading and description per known folder; unknown folders get a default.
TITLES = {
    "01_requirements/customer": (
        "Customer requirements (CR)",
        "Extract of the customer specification, ASPICE SYS.1. The ASIL is determined by the HARA (phase 2).",
    ),
    "01_requirements/system": (
        "System requirements (SYS-REQ)",
        "Derived from CR and FSR, ASPICE SYS.2.",
    ),
    "02_safety/02_hara": (
        "Hazards (H)",
        "Structured form of the HARA rows, ISO 26262-3. Derivation and method in hara.md.",
    ),
    "02_safety/03_fsc": (
        "Safety goals and functional safety concept (SG, FSR)",
        "ISO 26262-3. Safety goals with safe state and FTTI, and the FSR derived from them.",
    ),
    "02_safety/04_tsc": (
        "Technical safety concept (TSR)",
        "ISO 26262-4. Technical safety requirements and their allocation.",
    ),
    "02_safety/05_analyses": (
        "Safety analyses and risks (RISK)",
        "FMEA, FTA, FMEDA, DFA, STPA and the risks tracked.",
    ),
    "05_hardware": (
        "Hardware requirements and safety mechanisms (HW-REQ, SM)",
        "HWE.1-HWE.4, ISO 26262-5.",
    ),
    "06_software": (
        "Software requirements (SW-REQ)",
        "SWE.1-SWE.6, ISO 26262-6.",
    ),
    "07_verification/testcases": (
        "Test cases (TC)",
        "ASPICE SYS.4/SYS.5. Every test case references at least one requirement.",
    ),
}

ID_SPLIT = re.compile(r"^(.*?)-(\d+)$")

# Folders that hold no Requirements-as-Code records still get a listing, so that opening
# them shows what they are for instead of a bare file list.
FOLDER_DESC = {
    "01_requirements": ("Requirements",
        "Customer requirements (SYS.1) and system requirements (SYS.2), one record per file."),
    "02_safety": ("Functional safety — ISO 26262",
        "Concept phase and safety analyses, ordered along the standard: item definition, HARA, "
        "functional safety concept, technical safety concept, analyses."),
    "02_safety/01_item_definition": ("Item definition — ISO 26262-3",
        "Item boundary, interfaces, explicit exclusions, operating modes."),
    "03_model": ("MBSE model — MagicGrid / SysML v1.6",
        "MagicGrid matrix and the SysML views. Sources are text; rendered images are CI artefacts."),
    "03_model/plantuml": ("SysML views (PlantUML sources)",
        "One file per view. The file name prefix encodes the view type."),
    "03_model/exports": ("Rendered views (CI artefacts)",
        "Generated by CI, not committed. Regenerate locally with `plantuml -tsvg`."),
    "04_architecture": ("E/E architecture — ASPICE SYS.3",
        "Architecture blocks, interface table, and the allocation of requirements and functions."),
    "06_software": ("Software — SWE.1 … SWE.6, ISO 26262-6",
        "Software requirements, architecture and detailed design. Populated in phase 7."),
    "07_verification": ("Verification and validation — SYS.4 / SYS.5",
        "Test strategy, test cases and the generated reports."),
    "07_verification/reports": ("Generated evidence",
        "Traceability matrix and views. All files here are generated — edit the records instead."),
    "08_safety_case": ("Safety case — ISO 26262-2",
        "GSN argumentation, work product status, confirmation measures. Populated in phase 9."),
    "09_process": ("Process — SUP and MAN.3",
        "Plans, assumptions, project status, templates and the original commissioning prompt."),
    "09_process/plans": ("Plans", "Tool qualification and further project plans."),
    "09_process/prompts": ("Commissioning documents",
        "The original German meta-prompt that defines phases 0–11. Deliberately unchanged."),
    "tools": ("CI scripts",
        "Traceability check and generators. Standard library only — see the tool qualification note."),
    "tools/hooks": ("Git hooks",
        "Install with: ln -sf ../../tools/hooks/pre-commit .git/hooks/pre-commit"),
}

# Prefix convention, shown in the PlantUML folder listing.
PUML_PREFIX = {
    "ctx": "Context", "uc": "Use case", "req": "Requirements", "act": "Activity",
    "seq": "Sequence", "stm": "State machine", "bdd": "Block definition (BDD)",
    "ibd": "Internal block (IBD)", "par": "Parametric",
}


def file_purpose(path: Path) -> str:
    """Extracts a one-line purpose from a file, so the listing is not just file names."""
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4000]
    except OSError:
        return ""
    if path.suffix == ".puml":
        for line in head.splitlines():
            if line.strip().startswith("title "):
                return line.strip()[6:].strip()
    elif path.suffix == ".md":
        for line in head.splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    elif path.suffix == ".py":
        parts = head.split('"""')
        if len(parts) > 1:
            return parts[1].strip().splitlines()[0]
    elif path.suffix in (".yml", ".yaml"):
        for line in head.splitlines():
            if line.startswith("name:"):
                return line[5:].strip()
    elif path.suffix == ".html":
        m = re.search(r"<title>(.*?)</title>", head, re.S)
        if m:
            return " ".join(m.group(1).split())
    return ""


def sort_key(rid: str):
    """Sorts CR-2 before CR-10 (numeric rather than lexicographic)."""
    m = ID_SPLIT.match(rid)
    return (m.group(1), int(m.group(2))) if m else (rid, 0)


def short(text: str, limit: int = 130) -> str:
    """Truncates the requirement text for the table column and escapes pipes."""
    t = " ".join(str(text).split()).replace("|", "\\|")
    return t if len(t) <= limit else t[: limit - 1].rstrip() + "…"


def collect(root: Path) -> dict[Path, list[dict]]:
    """Collects all records, grouped by folder."""
    groups: dict[Path, list[dict]] = {}
    for path in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.name == "README.md":
            continue
        try:
            fm = parse_front_matter(path.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not fm or "id" not in fm:
            continue
        for field in LIST_FIELDS:
            val = fm.get(field)
            if val is None:
                fm[field] = []
            elif isinstance(val, str):
                fm[field] = [val] if val.strip() else []
        fm["_name"] = path.name
        groups.setdefault(path.parent, []).append(fm)
    return groups


def render(folder_rel: str, records: list[dict], upstream: dict, downstream: dict,
           others: list = ()) -> str:
    title, desc = TITLES.get(
        folder_rel, (f"Records in `{folder_rel}`", "Automatically generated overview.")
    )
    records = sorted(records, key=lambda r: sort_key(str(r["id"])))
    # Relative path back to the repo root - folders sit at different depths.
    up_to_root = "../" * len(folder_rel.split("/"))

    lines = [
        f"# {title}",
        "",
        MARKER,
        "",
        desc,
        "",
        f"**{len(records)} records.** Click an ID to open the record.",
        "",
        "| ID | Text | Type | ASIL | Status | Upstream | Downstream |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in records:
        rid = str(r["id"])
        up = ", ".join(sorted(upstream.get(rid, []))) or "—"
        dn = ", ".join(sorted(downstream.get(rid, []))) or "—"
        lines.append(
            "| [{id}]({file}) | {text} | {typ} | {asil} | {status} | {up} | {dn} |".format(
                id=rid,
                file=r["_name"],
                text=short(r.get("text", ""), 90),
                typ=r.get("type", "—"),
                asil=r.get("asil", "—"),
                status=r.get("status", "—"),
                up=short(up, 45),
                dn=short(dn, 45),
            )
        )

    # Roll-up by status and ASIL
    def tally(field: str) -> str:
        counts: dict[str, int] = {}
        for r in records:
            counts[str(r.get(field, "—"))] = counts.get(str(r.get(field, "—")), 0) + 1
        return " · ".join(f"{k}: {v}" for k, v in sorted(counts.items()))

    # Grouped view: a record appears under every element it is allocated to. A folder could
    # only give it one home, which is why this is a section and not a subfolder.
    buckets: dict[str, list] = {}
    for r in records:
        for el in r["allocated_to"]:
            buckets.setdefault(el, []).append(str(r["id"]))
    total_entries = sum(len(v) for v in buckets.values())
    dominance = max((len(v) for v in buckets.values()), default=0) / (total_entries or 1)
    if (len(records) >= GROUP_MIN_RECORDS and len(buckets) >= GROUP_MIN_BUCKETS
            and dominance < GROUP_MAX_DOMINANCE):
        lines += ["", "## By allocated element", "",
                  "A record appears under every element it is allocated to — allocation is",
                  "many-to-many, which is why this is a grouping and not a folder split.", ""]
        for el, ids in sorted(buckets.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            links = ", ".join(
                f"[{i}]({i}.md)" if any(str(r["id"]) == i for r in records) else i
                for i in sorted(ids, key=sort_key)
            )
            lines += [f"**{el}** ({len(ids)})", "", links, ""]

    if others:
        lines += ["", "## Other documents in this folder", "",
                  "| File | Purpose |", "|---|---|"]
        for f in others:
            lines.append(f"| [{f.name}]({f.name}) | {file_purpose(f) or '—'} |")

    lines += [
        "",
        f"**Status:** {tally('status')}",
        "",
        f"**ASIL:** {tally('asil')}",
        "",
        "---",
        "",
        "**Upstream** is what a record derives from, **downstream** what derives from it, allocates",
        "to it or verifies it. Graphical views of the same links:",
        f"[`traceability_views.md`]({up_to_root}07_verification/reports/traceability_views.md).",
        "",
        "This overview is generated by `tools/gen_index.py` and checked for freshness in CI.",
        "Make changes to the record, not to this file.",
        "",
    ]
    return "\n".join(lines)


def render_listing(root: Path, folder: Path, subfolders: list, files: list) -> str:
    rel = folder.relative_to(root).as_posix()
    title, desc = FOLDER_DESC.get(rel, (f"`{rel}`", "Contents of this folder."))
    lines = [f"# {title}", "", MARKER, "", desc, ""]

    if rel == "03_model/plantuml":
        lines += ["**File name prefixes**", "",
                  "| Prefix | View type |", "|---|---|"]
        lines += [f"| `{p}_` | {n} |" for p, n in sorted(PUML_PREFIX.items())]
        lines += [""]

    if subfolders:
        lines += ["## Subfolders", "", "| Folder | Contents |", "|---|---|"]
        for sub in subfolders:
            srel = sub.relative_to(root).as_posix()
            stitle = FOLDER_DESC.get(srel, (None, None))[0]
            if stitle is None:
                stitle = TITLES.get(srel, (f"`{sub.name}`",))[0]
            lines.append(f"| [`{sub.name}/`]({sub.name}/) | {stitle} |")
        lines += [""]

    if files:
        lines += ["## Files", "", "| File | Purpose |", "|---|---|"]
        for f in files:
            lines.append(f"| [{f.name}]({f.name}) | {file_purpose(f) or '—'} |")
        lines += [""]

    lines += ["---", "",
              "This listing is generated by `tools/gen_index.py` and checked for freshness in CI.",
              ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".", help="repo root (default: .)")
    ap.add_argument("--check", action="store_true", help="check only, write nothing")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: root not found: {root}", file=sys.stderr)
        return 2

    groups = collect(root)

    # Global link index across all folders: upstream = derives from, downstream = everything
    # that points back at this record by any relation.
    all_recs = {str(r["id"]): r for recs in groups.values() for r in recs}
    upstream: dict[str, set] = {}
    downstream: dict[str, set] = {}
    for rid, rec in all_recs.items():
        for parent in rec["derived_from"]:
            if parent in all_recs:
                upstream.setdefault(rid, set()).add(parent)
                downstream.setdefault(parent, set()).add(rid)
        for field in ("allocated_to", "verified_by"):
            for ref in rec[field]:
                if ref in all_recs:
                    downstream.setdefault(rid, set()).add(ref)
                    upstream.setdefault(ref, set()).add(rid)

    if not groups:
        print("No records found - nothing to do.")
        return 0

    stale: list[str] = []
    written: list[str] = []

    record_files = {
        folder: {r["_name"] for r in recs} for folder, recs in groups.items()
    }

    # Every folder that holds content gets an index: record folders get the record table,
    # all others a listing. The repo root is excluded - its README is hand-written.
    targets: dict[Path, str] = {}
    for folder in sorted({p for p in root.rglob("*") if p.is_dir()} | set(groups)):
        rel_parts = folder.relative_to(root).parts
        if any(part in SKIP_DIRS for part in rel_parts) or not rel_parts:
            continue
        others = sorted(
            f for f in folder.iterdir()
            if f.is_file() and f.name not in ("README.md", ".gitkeep")
            and f.name not in record_files.get(folder, set())
        )
        subs = sorted(
            d for d in folder.iterdir()
            if d.is_dir() and d.name not in SKIP_DIRS
            and any(x.name not in (".gitkeep",) for x in d.iterdir())
        )
        if folder in groups:
            rel = folder.relative_to(root).as_posix()
            targets[folder] = render(rel, groups[folder], upstream, downstream, others)
        elif others or subs or folder.relative_to(root).as_posix() in FOLDER_DESC:
            # Folders that are still empty but have a documented purpose get a stub,
            # so that opening them says what they are for and when they get filled.
            targets[folder] = render_listing(root, folder, subs, others)

    for folder, content in sorted(targets.items()):
        rel = folder.relative_to(root).as_posix()
        target = folder / "README.md"

        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if MARKER not in existing:
                print(
                    f"WARNING: {rel}/README.md is not generated (no marker) "
                    "- it will not be overwritten.",
                    file=sys.stderr,
                )
                continue
            if existing == content:
                continue

        if args.check:
            stale.append(rel)
        else:
            target.write_text(content, encoding="utf-8")
            n = len(groups[folder]) if folder in groups else 0
            what = f"{n} records" if n else "listing"
            written.append(f"{rel}/README.md ({what})")

    # Size advice, printed once per run - not a finding, and never silent.
    for folder, recs in sorted(groups.items()):
        if len(recs) <= SPLIT_THRESHOLD:
            continue
        rel = folder.relative_to(root).as_posix()
        multi = sum(1 for r in recs if len(r["allocated_to"]) > 1)
        print(f"\nNOTE: {rel} holds {len(recs)} records (threshold {SPLIT_THRESHOLD}).",
              file=sys.stderr)
        if multi:
            print(f"      Do NOT split by allocated element: {multi} of {len(recs)} records are "
                  f"allocated to more than one element, so every filing decision would be "
                  f"arbitrary. Split only by a field that is single-valued for every record.",
                  file=sys.stderr)
        else:
            print("      `allocated_to` is single-valued for every record here, so a split by "
                  "element is viable.", file=sys.stderr)

    if args.check:
        if stale:
            print("Stale overviews:")
            for s in stale:
                print(f"  - {s}/README.md")
            print("\nPlease run 'python3 tools/gen_index.py' and commit the result.")
            return 1
        print(f"All overviews up to date ({len(targets)} folders).")
        return 0

    if written:
        print("Updated:")
        for w in written:
            print(f"  - {w}")
    else:
        print(f"All overviews already up to date ({len(targets)} folders).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
