#!/usr/bin/env python3
"""Generates a DOORS-like browser for the Requirements-as-Code records and the model views.

Output:
    07_verification/reports/requirements_browser.html

The page is a *derived artefact*. The records under 01_requirements/, 02_safety/,
05_hardware/, 06_software/ and 07_verification/ remain the source, and the PlantUML
sources under 03_model/plantuml/ remain the source of the diagrams. Nothing is authored
here that is not in a record.

Layout follows the way a requirements management tool presents a project:

    modules (left)  ->  record list of the selected module (middle)  ->  record detail (right)

A module is simply a folder of records; the folder structure of the repo is the module
structure. Records carry their attributes, their upstream and downstream links, and the
narrative body of the record file. Diagrams are rendered to SVG and embedded.

Standard library only -- no third-party dependency, which keeps the tool-qualification
argument (ISO 26262-8, Clause 11) as small as possible. PlantUML is invoked as an external
process when available; without it the diagrams degrade to their source text and the page
says so rather than pretending the diagram is missing.

Usage:
    python3 tools/gen_req_browser.py             # write/update the page
    python3 tools/gen_req_browser.py --check     # check only, exit 1 if stale
    python3 tools/gen_req_browser.py --root DIR  # different repo root

Exit 0 = up to date or written, 1 = stale (with --check only), 2 = error.

NOTE: like trace_check.py, gen_index.py and gen_trace_graph.py this is a
tool-qualification candidate -- see 09_process/plans/tool_qualification.md. It puts
JavaScript between the record and its presentation, so it is a convenience for reading and
reviewing, never the artefact to cite as evidence. Completeness is argued from
traceability_matrix.md and trace_check.py, not from this page.
"""

from __future__ import annotations

import argparse
import base64
import html
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_check import ASIL_ORDER, kpis, load_records  # noqa: E402

OUT_REL = "07_verification/reports/requirements_browser.html"
PUML_DIR = "03_model/plantuml"
MARKER = "generated by tools/gen_req_browser.py -- do not edit manually"

# Friendly module titles. A folder that is not listed falls back to its path.
MODULE_TITLES = {
    "01_requirements/customer": "Customer requirements",
    "01_requirements/system": "System requirements",
    "02_safety/02_hara": "Hazards (HARA)",
    "02_safety/03_fsc": "Safety goals and functional safety concept",
    "02_safety/04_tsc": "Technical safety concept",
    "02_safety/05_analyses": "Risks",
    "05_hardware": "Hardware requirements and safety mechanisms",
    "06_software": "Software requirements and design",
    "07_verification/testcases": "Test cases",
}

# ASPICE process / ISO 26262 part per module, shown as the module subtitle.
MODULE_PROCESS = {
    "01_requirements/customer": "ASPICE SYS.1",
    "01_requirements/system": "ASPICE SYS.2",
    "02_safety/02_hara": "ISO 26262-3",
    "02_safety/03_fsc": "ISO 26262-3",
    "02_safety/04_tsc": "ISO 26262-4",
    "02_safety/05_analyses": "ISO 26262-9",
    "05_hardware": "ASPICE HWE.1, ISO 26262-5",
    "06_software": "ASPICE SWE.1, ISO 26262-6",
    "07_verification/testcases": "ASPICE SYS.4/SYS.5",
}

# Narrative work products that are not records but that a reader wants reachable.
DOCUMENTS = [
    ("02_safety/01_item_definition/item_definition.md", "Item definition"),
    ("02_safety/02_hara/hara.md", "HARA"),
    ("02_safety/02_hara/operational_situations.md", "Operational situations"),
    ("02_safety/02_hara/sec_classification.md", "S/E/C classification"),
    ("04_architecture/ee_architecture.md", "E/E architecture"),
    ("04_architecture/allocation.md", "Function allocation"),
    ("03_model/magicgrid.md", "MagicGrid matrix"),
    ("05_hardware/hw_architecture.md", "Hardware architecture"),
    ("05_hardware/analysis_current_sensing.md", "Analysis: current sensing"),
    ("05_hardware/analysis_sm01_coverage.md", "Analysis: SM-01 coverage"),
    ("05_hardware/analysis_supply_and_transients.md", "Analysis: supply and transients"),
    ("05_hardware/analysis_thermal_derating.md", "Analysis: thermal derating"),
    ("05_hardware/hw_verification_plan.md", "Hardware verification plan"),
    ("07_verification/reports/traceability_matrix.md", "Traceability matrix"),
    ("07_verification/reports/trace_explorer.html", "Trace explorer"),
    ("09_process/assumptions.md", "Assumptions"),
    ("09_process/project_status.md", "Project status"),
]

KIND_COLOR = {
    "H": "#c07d29",
    "CR": "#3b6ea5",
    "SG": "#b05252",
    "FSR": "#b05252",
    "TSR": "#7a5ea8",
    "SYS-REQ": "#3b6ea5",
    "HW-REQ": "#4a8a4a",
    "SW-REQ": "#4a8a4a",
    "SM": "#4a8a4a",
    "TC": "#c07d29",
    "RISK": "#9a9aa5",
}


def kind_of(rid: str) -> str:
    return rid.rsplit("-", 1)[0]


def sort_key(rid: str):
    kind, _, num = rid.rpartition("-")
    try:
        return (kind, int(num))
    except ValueError:
        return (kind, 0)


# ------------------------------------------------------------------ record body


def body_of(path: Path) -> str:
    """Return the narrative part of a record file, i.e. everything after the front matter."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    if end == -1:
        return ""
    return text[end + 4 :].lstrip("\n")


_INLINE_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*([^*\n]+)\*(?!\*)")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_STRIKE = re.compile(r"~~([^~]+)~~")


def inline_md(text: str) -> str:
    """Escape, then apply the inline Markdown the records actually use."""
    out = html.escape(text)
    out = _INLINE_CODE.sub(lambda m: f"<code>{m.group(1)}</code>", out)
    out = _BOLD.sub(lambda m: f"<strong>{m.group(1)}</strong>", out)
    out = _STRIKE.sub(lambda m: f"<del>{m.group(1)}</del>", out)
    out = _ITALIC.sub(lambda m: f"<em>{m.group(1)}</em>", out)
    out = _LINK.sub(lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>', out)
    return out


def md_to_html(md: str) -> str:
    """A deliberately small Markdown subset: what the record bodies use, nothing more."""
    lines = md.split("\n")
    out: list[str] = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # fenced code
        if stripped.startswith("```"):
            i += 1
            buf = []
            while i < n and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            out.append("<pre class='code'>" + html.escape("\n".join(buf)) + "</pre>")
            continue

        # heading
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            lvl = min(len(m.group(1)) + 2, 6)
            out.append(f"<h{lvl}>{inline_md(m.group(2))}</h{lvl}>")
            i += 1
            continue

        # table
        if stripped.startswith("|") and i + 1 < n and re.match(r"^\|[\s:\-|]+\|$", lines[i + 1].strip()):
            header = [c.strip() for c in stripped.strip("|").split("|")]
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            thead = "".join(f"<th>{inline_md(c)}</th>" for c in header)
            tbody = "".join(
                "<tr>" + "".join(f"<td>{inline_md(c)}</td>" for c in r) + "</tr>" for r in rows
            )
            out.append(f"<div class='tw'><table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table></div>")
            continue

        # blockquote
        if stripped.startswith(">"):
            buf = []
            while i < n and lines[i].strip().startswith(">"):
                buf.append(lines[i].strip().lstrip(">").strip())
                i += 1
            out.append("<blockquote>" + inline_md(" ".join(buf)) + "</blockquote>")
            continue

        # list
        if re.match(r"^([-*]|\d+\.)\s+", stripped):
            ordered = bool(re.match(r"^\d+\.\s+", stripped))
            items = []
            while i < n and re.match(r"^([-*]|\d+\.)\s+", lines[i].strip()):
                items.append(re.sub(r"^([-*]|\d+\.)\s+", "", lines[i].strip()))
                i += 1
                # continuation lines of the same item
                while i < n and lines[i].startswith(("  ", "\t")) and lines[i].strip() \
                        and not re.match(r"^([-*]|\d+\.)\s+", lines[i].strip()):
                    items[-1] += " " + lines[i].strip()
                    i += 1
            tag = "ol" if ordered else "ul"
            out.append(f"<{tag}>" + "".join(f"<li>{inline_md(it)}</li>" for it in items) + f"</{tag}>")
            continue

        # paragraph
        buf = []
        while i < n and lines[i].strip() and not lines[i].strip().startswith(("#", ">", "|", "```")) \
                and not re.match(r"^([-*]|\d+\.)\s+", lines[i].strip()):
            buf.append(lines[i].strip())
            i += 1
        out.append("<p>" + inline_md(" ".join(buf)) + "</p>")

    return "".join(out)


# -------------------------------------------------------------------- mapping

MAPPING_REL = "09_process/aspice_mapping.md"

LEVEL_ORDER = ["concept", "system", "hardware", "software", "supporting"]
LEVEL_TITLE = {
    "concept": "Concept phase",
    "system": "System level",
    "hardware": "Hardware level",
    "software": "Software level",
    "supporting": "Supporting and management processes",
}


def parse_mapping(root: Path) -> list[dict]:
    """Read the process-area table from 09_process/aspice_mapping.md.

    The mapping is committed data on purpose: which process area a work product belongs to
    is a reviewable statement, not something this script should decide.
    """
    path = root / MAPPING_REL
    if not path.is_file():
        print(f"  ! {MAPPING_REL} not found - process views will be empty", file=sys.stderr)
        return []

    areas: list[dict] = []
    in_table = False
    for line in path.read_text(encoding="utf-8").split("\n"):
        line = line.strip()
        if not line.startswith("|"):
            in_table = False
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 7:
            continue
        if cells[0] == "Area":
            in_table = True
            continue
        if re.match(r"^[\s:\-]+$", cells[0]):
            continue
        if not in_table:
            continue

        def split(v: str) -> list[str]:
            return [] if v == "-" else [x.strip() for x in v.split(",") if x.strip()]

        areas.append({
            "id": cells[0],
            "framework": cells[1],
            "name": cells[2],
            "level": cells[3],
            "side": cells[4],
            "rec_src": split(cells[5]),
            "doc_src": split(cells[6]),
        })
    return areas


def resolve_areas(areas: list[dict], items: dict, root: Path) -> list[dict]:
    """Attach the concrete records and documents each area owns."""
    for area in areas:
        ids: list[str] = []
        for src in area["rec_src"]:
            if src.startswith("path:"):
                folder = src[5:]
                ids += [i for i, r in items.items() if r["file"].startswith(folder + "/")]
            elif src.startswith("id:"):
                ids += [i for i in items if i.startswith(src[3:])]
        area["ids"] = sorted(set(ids), key=sort_key)

        docs = []
        for d in area["doc_src"]:
            docs.append({"path": d, "exists": (root / d).exists()})
        area["docs"] = docs
        area["empty"] = not area["ids"] and not docs
    return areas


# ------------------------------------------------------------------- diagrams


def render_diagrams(root: Path) -> tuple[list[dict], bool]:
    """Render every PlantUML source to SVG. Returns (diagrams, plantuml_available)."""
    puml_dir = root / PUML_DIR
    if not puml_dir.is_dir():
        return [], True

    available = shutil.which("plantuml") is not None
    diagrams: list[dict] = []

    for path in sorted(puml_dir.glob("*.puml")):
        src = path.read_text(encoding="utf-8")
        title = ""
        for line in src.split("\n"):
            if line.strip().startswith("title "):
                title = line.strip()[6:].strip()
                break

        svg = ""
        if available:
            try:
                res = subprocess.run(
                    ["plantuml", "-tsvg", "-pipe"],
                    input=src.encode("utf-8"),
                    capture_output=True,
                    timeout=120,
                )
                if res.returncode == 0 and res.stdout.lstrip()[:4] in (b"<svg", b"<?xm"):
                    svg = base64.b64encode(res.stdout).decode("ascii")
                else:
                    err = res.stderr.decode("utf-8", "replace").strip()
                    print(f"  ! {path.name}: PlantUML returned {res.returncode} {err[:200]}",
                          file=sys.stderr)
            except (OSError, subprocess.SubprocessError) as exc:
                print(f"  ! {path.name}: {exc}", file=sys.stderr)

        diagrams.append(
            {
                "name": path.stem,
                "title": title or path.stem,
                "file": str(path.relative_to(root)),
                "svg": svg,
                "src": src,
            }
        )

    return diagrams, available


# ---------------------------------------------------------------------- model


def build_model(root: Path) -> dict:
    records, load_findings = load_records(root)
    if load_findings:
        for f in load_findings:
            print(f"  ! {f['severity']}: {f['where']}: {f['message']}", file=sys.stderr)

    # Reverse links: who derives from me, who verifies me, who allocates to me.
    children: dict[str, list[str]] = {rid: [] for rid in records}
    verifies: dict[str, list[str]] = {rid: [] for rid in records}
    for rid, rec in records.items():
        for parent in rec.get("derived_from", []):
            children.setdefault(parent, []).append(rid)
        for target in rec.get("verified_by", []):
            verifies.setdefault(target, []).append(rid)

    modules: dict[str, dict] = {}
    items: dict[str, dict] = {}

    for rid, rec in sorted(records.items(), key=lambda kv: sort_key(kv[0])):
        rel = rec["_file"]
        folder = str(Path(rel).parent)
        mod = modules.setdefault(
            folder,
            {
                "id": folder,
                "title": MODULE_TITLES.get(folder, folder),
                "process": MODULE_PROCESS.get(folder, ""),
                "path": folder,
                "ids": [],
            },
        )
        mod["ids"].append(rid)

        items[rid] = {
            "id": rid,
            "kind": kind_of(rid),
            "text": rec.get("text", ""),
            "type": rec.get("type", ""),
            "asil": rec.get("asil", ""),
            "status": rec.get("status", ""),
            "source": rec.get("source", ""),
            "rationale": rec.get("rationale", ""),
            "up": rec.get("derived_from", []),
            "down": sorted(children.get(rid, []), key=sort_key),
            "alloc": rec.get("allocated_to", []),
            "vby": rec.get("verified_by", []),
            "verifies": sorted(verifies.get(rid, []), key=sort_key),
            "tags": rec.get("tags", []),
            "file": rel,
            "body": md_to_html(body_of(root / rel)),
        }

    areas = resolve_areas(parse_mapping(root), items, root)

    diagrams, plantuml_ok = render_diagrams(root)

    documents = [
        {"path": p, "title": t} for p, t in DOCUMENTS if (root / p).exists()
    ]

    # KPIs come from trace_check.kpis() verbatim rather than being recomputed here.
    # Two implementations of "coverage" would drift, and the gate is the authority --
    # a browser that quietly reports a different number than the check is worse than one
    # that reports none.
    stats = dict(kpis(records))

    return {
        "modules": [modules[k] for k in sorted(modules)],
        "areas": areas,
        "levels": [{"id": l, "title": LEVEL_TITLE[l]} for l in LEVEL_ORDER],
        "items": items,
        "diagrams": diagrams,
        "documents": documents,
        "plantuml": plantuml_ok,
        "stats": stats,
        "ndiagrams": len(diagrams),
        "asils": sorted({r["asil"] for r in items.values() if r["asil"]},
                        key=lambda a: (ASIL_ORDER.get(a.split("(")[0].strip().upper(), 9), a)),
        "statuses": sorted({r["status"] for r in items.values() if r["status"]}),
        "kinds": sorted({r["kind"] for r in items.values()}),
        "colors": KIND_COLOR,
    }


# ----------------------------------------------------------------------- page

PAGE = r"""<!DOCTYPE html>
<!-- __MARKER__ -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Requirements browser - Adaptive front lighting system</title>
<style>
  :root { --bg:#ffffff; --fg:#1a2430; --muted:#6b7a8d; --line:#d8e0ea; --panel:#f7fafd;
          --accent:#3b6ea5; --warn:#b05252; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0f1419; --fg:#e2e8ef; --muted:#95a3b4; --line:#2a3542; --panel:#161d25;
            --accent:#6fa3d8; --warn:#d98080; }
  }
  * { box-sizing:border-box; }
  html, body { height:100%; }
  body { margin:0; font:14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background:var(--bg); color:var(--fg); display:flex; flex-direction:column; }
  a { color:var(--accent); }

  header { border-bottom:1px solid var(--line); padding:10px 16px; display:flex;
           gap:14px; align-items:center; flex-wrap:wrap; background:var(--panel); }
  header h1 { font-size:15px; margin:0; font-weight:700; letter-spacing:.2px; }
  header .stats { color:var(--muted); font-size:12px; }
  header .grow { flex:1; }
  input, select { font:inherit; padding:5px 9px; border:1px solid var(--line); border-radius:7px;
                  background:var(--bg); color:var(--fg); }
  input#q { min-width:230px; }

  main { flex:1; display:flex; min-height:0; }
  nav { width:270px; border-right:1px solid var(--line); overflow:auto; padding:10px 0;
        background:var(--panel); flex-shrink:0; }
  nav h2 { font-size:11px; text-transform:uppercase; letter-spacing:.7px; color:var(--muted);
           margin:14px 16px 6px; }
  nav a.mod { display:block; padding:6px 16px; text-decoration:none; color:var(--fg); }
  nav a.mod:hover { background:var(--bg); }
  nav a.mod.sel { background:var(--bg); box-shadow:inset 3px 0 0 var(--accent); font-weight:600; }
  nav a.mod .sub { display:block; font-size:11px; color:var(--muted); font-weight:400; }
  nav a.mod .n { float:right; font-size:11px; color:var(--muted); font-weight:400; }

  section#content { flex:1; overflow:auto; padding:16px 20px 60px; min-width:0; }
  h2.title { margin:0 0 2px; font-size:18px; }
  p.sub { margin:0 0 16px; color:var(--muted); font-size:12px; }

  table { border-collapse:collapse; width:100%; font-size:13px; }
  th, td { text-align:left; padding:7px 9px; border-bottom:1px solid var(--line);
           vertical-align:top; }
  th { font-size:11px; text-transform:uppercase; letter-spacing:.5px; color:var(--muted);
       position:sticky; top:0; background:var(--bg); z-index:1; cursor:pointer; }
  tbody tr:hover { background:var(--panel); }
  td.id { white-space:nowrap; font-weight:600; }
  td.txt { max-width:640px; }
  .tw { overflow-x:auto; }

  .pill { display:inline-block; padding:1px 7px; border-radius:20px; font-size:11px;
          border:1px solid var(--line); white-space:nowrap; }
  .pill.kind { color:#fff; border:0; }
  .chip { display:inline-block; margin:2px 5px 2px 0; padding:2px 8px; border-radius:6px;
          border:1px solid var(--line); text-decoration:none; color:inherit; font-size:12px;
          background:var(--bg); white-space:nowrap; }
  .chip:hover { border-color:var(--accent); }
  .none { color:var(--muted); font-size:12px; }

  .grid { display:grid; grid-template-columns:150px 1fr; gap:7px 14px; margin:14px 0 20px;
          font-size:13px; }
  .grid dt { color:var(--muted); font-size:12px; }
  .grid dd { margin:0; }
  .card { border:1px solid var(--line); border-radius:9px; padding:14px 16px; background:var(--panel);
          margin-bottom:16px; }
  .card h3 { margin:0 0 8px; font-size:13px; text-transform:uppercase; letter-spacing:.6px;
             color:var(--muted); }
  .reqtext { font-size:15px; line-height:1.55; }
  .body { border-top:1px solid var(--line); padding-top:14px; }
  .body h3,.body h4,.body h5 { margin:16px 0 6px; font-size:14px; }
  .body p { margin:8px 0; }
  .body table { font-size:12px; margin:8px 0; }
  .body blockquote { margin:8px 0; padding:6px 12px; border-left:3px solid var(--line);
                     color:var(--muted); }
  pre.code { background:var(--panel); border:1px solid var(--line); border-radius:7px;
             padding:10px 12px; overflow-x:auto; font-size:12px; }
  code { background:var(--panel); padding:1px 5px; border-radius:4px; font-size:12.5px; }

  .diagram { background:#fff; border:1px solid var(--line); border-radius:9px; padding:12px;
             overflow:auto; }
  .diagram img { max-width:100%; display:block; margin:0 auto; }
  .banner { border:1px solid var(--warn); color:var(--warn); border-radius:8px; padding:9px 12px;
            margin-bottom:14px; font-size:13px; }
  button.link { background:none; border:0; color:var(--accent); cursor:pointer; font:inherit;
                padding:0; text-decoration:underline; }
  .foot { color:var(--muted); font-size:11px; margin-top:26px; border-top:1px solid var(--line);
          padding-top:10px; }
  select#grouping { width:calc(100% - 32px); margin:2px 16px 6px; }
  .vlevel { margin-bottom:22px; }
  .vlevel > h3 { margin:0 0 10px; font-size:12px; text-transform:uppercase; letter-spacing:.7px;
                 color:var(--muted); border-bottom:1px solid var(--line); padding-bottom:6px; }
  .vcols { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  .vcols > div > h4 { margin:0 0 8px; font-size:11px; text-transform:uppercase;
                      letter-spacing:.6px; color:var(--muted); font-weight:600; }
  .acard { display:block; border:1px solid var(--line); border-radius:9px; padding:10px 12px;
           margin-bottom:8px; text-decoration:none; color:inherit; background:var(--panel); }
  .acard:hover { border-color:var(--accent); }
  .acard .aid { font-weight:700; }
  .acard .an { color:var(--muted); font-size:12px; display:block; margin-top:2px; }
  .acard .ac { float:right; font-size:11px; color:var(--muted); }
  .acard.empty { background:none; border-style:dashed; }
  .acard.empty .aid, .acard.empty .an { color:var(--muted); }
  .doclist a { display:block; padding:4px 0; }
  .missing { color:var(--warn); }
  @media (max-width:1100px) { .vcols { grid-template-columns:1fr; } }
  @media (max-width:820px) { nav { display:none; } }
</style>
</head>
<body>
<header>
  <h1>Adaptive front lighting system</h1>
  <span class="stats" id="stats"></span>
  <span class="grow"></span>
  <input id="q" type="search" placeholder="Search id, text, rationale, element...">
  <select id="fKind"></select>
  <select id="fAsil"></select>
  <select id="fStatus"></select>
</header>
<main>
  <nav id="nav"></nav>
  <section id="content"></section>
</main>

<script id="data" type="application/json">__DATA__</script>
<script>
const D = JSON.parse(document.getElementById('data').textContent);
const items = D.items, mods = D.modules;
const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g, c =>
  ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

function kindPill(k) {
  const c = D.colors[k] || '#777';
  return `<span class="pill kind" style="background:${c}">${esc(k)}</span>`;
}
function chips(ids) {
  if (!ids || !ids.length) return '<span class="none">-</span>';
  return ids.map(id => items[id]
    ? `<a class="chip" href="#r/${encodeURIComponent(id)}">${esc(id)}</a>`
    : `<span class="chip" title="not a record">${esc(id)}</span>`).join('');
}

/* ---- filters ---- */
const F = { q:'', kind:'', asil:'', status:'' };
function fill(sel, label, values) {
  const el = document.getElementById(sel);
  el.innerHTML = `<option value="">${label}</option>` +
    values.map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join('');
}
fill('fKind', 'All types', D.kinds);
fill('fAsil', 'All ASIL', D.asils);
fill('fStatus', 'All statuses', D.statuses);

function matches(r) {
  if (F.kind && r.kind !== F.kind) return false;
  if (F.asil && r.asil !== F.asil) return false;
  if (F.status && r.status !== F.status) return false;
  if (F.q) {
    const hay = (r.id + ' ' + r.text + ' ' + r.rationale + ' ' + r.alloc.join(' ') + ' ' +
                 r.type + ' ' + r.file).toLowerCase();
    if (!hay.includes(F.q)) return false;
  }
  return true;
}

/* ---- navigation ---- */
function renderNav() {
  const cur = location.hash;
  const nav = document.getElementById('nav');
  const keepScroll = nav.scrollTop;
  // A record is "in" its module, so opening one keeps the module highlighted.
  let openMod = null;
  if (cur.startsWith('#r/')) {
    const r = items[decodeURIComponent(cur.slice(3))];
    if (r) openMod = (mods.find(m => m.ids.includes(r.id)) || {}).id;
  }
  let h = `<h2>Grouping</h2>
    <select id="grouping">
      <option value="aspice">ASPICE process areas</option>
      <option value="iso">ISO 26262 parts</option>
      <option value="folder">Repository folders</option>
    </select>
    <a class="mod${cur.startsWith('#v') || cur === '' ? ' sel' : ''}" href="#v/${grouping === 'folder' ? 'aspice' : grouping}">
       V-model overview<span class="sub">all process areas, populated or not</span></a>`;

  if (grouping === 'folder') {
    h += '<h2>Modules</h2>';
    for (const m of mods) {
      const n = m.ids.filter(id => matches(items[id])).length;
      const sel = (cur === '#m/' + encodeURIComponent(m.id) || m.id === openMod) ? ' sel' : '';
      h += `<a class="mod${sel}" href="#m/${encodeURIComponent(m.id)}">
              <span class="n">${n}/${m.ids.length}</span>${esc(m.title)}
              <span class="sub">${esc(m.path)}${m.process ? ' &middot; ' + esc(m.process) : ''}</span>
            </a>`;
    }
  } else {
    const fw = grouping === 'iso' ? 'ISO' : 'ASPICE';
    for (const lvl of D.levels) {
      const inLevel = D.areas.filter(a => a.framework === fw && a.level === lvl.id);
      if (!inLevel.length) continue;
      h += `<h2>${esc(lvl.title)}</h2>`;
      for (const a of inLevel) {
        const n = a.ids.filter(id => matches(items[id])).length;
        const sel = cur === '#a/' + encodeURIComponent(a.id) ? ' sel' : '';
        // Records and documents are different things; mixing them into one ratio made
        // an area with three documents and no records read as "0/3", i.e. as nothing done.
        const count = a.empty ? 'empty'
          : a.ids.length ? `${n}/${a.ids.length}`
          : `${a.docs.length} doc${a.docs.length > 1 ? 's' : ''}`;
        h += `<a class="mod${sel}" href="#a/${encodeURIComponent(a.id)}">
                <span class="n">${count}</span>${esc(a.id)}
                <span class="sub">${esc(a.name)}</span></a>`;
      }
    }
  }
  h += '<h2>Model views</h2>';
  for (const d of D.diagrams) {
    const sel = cur === '#d/' + encodeURIComponent(d.name) ? ' sel' : '';
    h += `<a class="mod${sel}" href="#d/${encodeURIComponent(d.name)}">${esc(d.name)}
            <span class="sub">${esc(d.title)}</span></a>`;
  }
  h += '<h2>Documents</h2>';
  for (const doc of D.documents) {
    h += `<a class="mod" href="../../${doc.path}">${esc(doc.title)}
            <span class="sub">${esc(doc.path)}</span></a>`;
  }
  nav.innerHTML = h;
  nav.scrollTop = keepScroll;
  const g = document.getElementById('grouping');
  g.value = grouping;
  // The grouping goes into the URL like everything else, so a reload keeps it and a
  // link can point at "the ISO view" rather than at whatever the recipient last chose.
  g.onchange = e => {
    grouping = e.target.value;
    location.hash = grouping === 'folder' ? '#m/' + encodeURIComponent(mods[0].id)
                                          : '#v/' + grouping;
  };
}

/* ---- views ---- */
let grouping = 'aspice';
let sortCol = 'id', sortAsc = true;
const COLS = [['id','ID'],['text','Text'],['type','Type'],['asil','ASIL'],
              ['status','Status'],['up','Derived from'],['down','Refined by'],['vby','Verified by']];

function table(ids) {
  const rows = ids.map(id => items[id]).filter(matches);
  rows.sort((a, b) => {
    let x = a[sortCol], y = b[sortCol];
    if (Array.isArray(x)) { x = x.length; y = y.length; }
    if (sortCol === 'id') {
      const na = parseInt(a.id.split('-').pop(), 10), nb = parseInt(b.id.split('-').pop(), 10);
      x = a.kind + String(na).padStart(4, '0'); y = b.kind + String(nb).padStart(4, '0');
    }
    return (x > y ? 1 : x < y ? -1 : 0) * (sortAsc ? 1 : -1);
  });
  if (!rows.length) return '<p class="none">No record matches the current filter.</p>';
  const head = COLS.map(([k, l]) =>
    `<th data-c="${k}">${l}${sortCol === k ? (sortAsc ? ' &uarr;' : ' &darr;') : ''}</th>`).join('');
  const body = rows.map(r => `<tr>
      <td class="id">${kindPill(r.kind)} <a href="#r/${encodeURIComponent(r.id)}">${esc(r.id)}</a></td>
      <td class="txt">${esc(r.text)}</td>
      <td>${esc(r.type)}</td>
      <td><span class="pill">${esc(r.asil || '-')}</span></td>
      <td><span class="pill">${esc(r.status)}</span></td>
      <td>${chips(r.up)}</td>
      <td>${chips(r.down)}</td>
      <td>${chips(r.vby.length ? r.vby : r.verifies)}</td>
    </tr>`).join('');
  return `<div class="tw"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
}

function viewModule(id) {
  const m = mods.find(x => x.id === id) || mods[0];
  return `<h2 class="title">${esc(m.title)}</h2>
          <p class="sub">${esc(m.path)}${m.process ? ' &middot; ' + esc(m.process) : ''}
             &middot; ${m.ids.length} records</p>${table(m.ids)}`;
}

function viewRecord(id) {
  const r = items[id];
  if (!r) return `<p class="none">Unknown record ${esc(id)}.</p>`;
  return `<h2 class="title">${kindPill(r.kind)} ${esc(r.id)}</h2>
    <p class="sub">${esc(r.file)}</p>
    <div class="card"><h3>Requirement text</h3>
      <div class="reqtext">${esc(r.text)}</div></div>
    <dl class="grid">
      <dt>Type</dt><dd>${esc(r.type || '-')}</dd>
      <dt>ASIL</dt><dd><span class="pill">${esc(r.asil || '-')}</span></dd>
      <dt>Status</dt><dd><span class="pill">${esc(r.status || '-')}</span></dd>
      <dt>Source</dt><dd>${esc(r.source || '-')}</dd>
      <dt>Derived from</dt><dd>${chips(r.up)}</dd>
      <dt>Refined by</dt><dd>${chips(r.down)}</dd>
      <dt>Allocated to</dt><dd>${r.alloc.length
        ? r.alloc.map(a => `<span class="chip">${esc(a)}</span>`).join('') : '<span class="none">-</span>'}</dd>
      <dt>Verified by</dt><dd>${chips(r.vby)}</dd>
      ${r.verifies.length ? `<dt>Verifies</dt><dd>${chips(r.verifies)}</dd>` : ''}
      ${r.tags.length ? `<dt>Tags</dt><dd>${r.tags.map(t => `<span class="chip">${esc(t)}</span>`).join('')}</dd>` : ''}
    </dl>
    ${r.rationale ? `<div class="card"><h3>Rationale</h3><div>${esc(r.rationale)}</div></div>` : ''}
    ${r.body ? `<div class="body">${r.body}</div>` : ''}
    <p class="foot">Source of truth is the record file, not this page:
       <a href="../../${r.file}">${esc(r.file)}</a></p>`;
}

function viewDiagram(name) {
  const d = D.diagrams.find(x => x.name === name);
  if (!d) return '<p class="none">Unknown diagram.</p>';
  const img = d.svg
    ? `<div class="diagram"><img alt="${esc(d.title)}" src="data:image/svg+xml;base64,${d.svg}"></div>`
    : `<div class="banner">Not rendered - PlantUML was unavailable when this page was generated.
         The source below is authoritative either way.</div>`;
  return `<h2 class="title">${esc(d.title)}</h2>
    <p class="sub">${esc(d.file)}</p>${img}
    <p style="margin:12px 0"><button class="link" onclick="
       var e=document.getElementById('src');
       e.style.display = e.style.display === 'none' ? 'block' : 'none';">Show / hide source</button></p>
    <pre class="code" id="src" style="display:none">${esc(d.src)}</pre>`;
}

function areaCard(a) {
  const n = a.ids.filter(id => matches(items[id])).length;
  const bits = [];
  if (a.ids.length) bits.push(`${n}/${a.ids.length} records`);
  if (a.docs.length) bits.push(`${a.docs.length} document${a.docs.length > 1 ? 's' : ''}`);
  return `<a class="acard${a.empty ? ' empty' : ''}" href="#a/${encodeURIComponent(a.id)}">
            <span class="ac">${bits.length ? bits.join(' &middot; ') : 'not started'}</span>
            <span class="aid">${esc(a.id)}</span>
            <span class="an">${esc(a.name)}</span></a>`;
}

function viewVModel() {
  const fw = grouping === 'iso' ? 'ISO' : 'ASPICE';
  const label = fw === 'ISO' ? 'ISO 26262 parts' : 'ASPICE process areas';
  let h = `<h2 class="title">V-model overview</h2>
    <p class="sub">${esc(label)} &middot; allocation from
       <a href="../../09_process/aspice_mapping.md">09_process/aspice_mapping.md</a>.
       An area with a dashed border has no work product yet -- that is the project's state,
       not a rendering gap.</p>`;

  for (const lvl of D.levels) {
    const inLevel = D.areas.filter(a => a.framework === fw && a.level === lvl.id);
    if (!inLevel.length) continue;
    const left = inLevel.filter(a => a.side === 'left');
    const right = inLevel.filter(a => a.side === 'right');
    const sup = inLevel.filter(a => a.side === 'supporting');
    h += `<div class="vlevel"><h3>${esc(lvl.title)}</h3>`;
    // Two columns only where both arms exist. The ISO 26262 parts are not split into a
    // specification and a verification arm, so forcing the layout would print an empty
    // "Verification" column at every level and imply a gap that is not there.
    if (left.length && right.length) {
      h += `<div class="vcols">
              <div><h4>Specification</h4>${left.map(areaCard).join('')}</div>
              <div><h4>Verification</h4>${right.map(areaCard).join('')}</div>
            </div>`;
    } else if (left.length || right.length) {
      h += left.concat(right).map(areaCard).join('');
    }
    if (sup.length) h += sup.map(areaCard).join('');
    h += '</div>';
  }
  return h;
}

function viewArea(id) {
  const a = D.areas.find(x => x.id === id);
  if (!a) return `<p class="none">Unknown process area ${esc(id)}.</p>`;
  const side = a.side === 'left' ? 'specification' : a.side === 'right' ? 'verification' : 'supporting';
  let h = `<h2 class="title">${esc(a.id)} &mdash; ${esc(a.name)}</h2>
    <p class="sub">${esc(a.framework === 'ISO' ? 'ISO 26262' : 'ASPICE')} &middot;
       ${esc(a.level)} level &middot; ${esc(side)}</p>`;

  if (a.empty) {
    h += `<div class="banner">No work product is allocated to this area yet.
            The allocation itself is stated in
            <a href="../../09_process/aspice_mapping.md">aspice_mapping.md</a>;
            an empty area means the phase that would produce it has not been run.</div>`;
  }
  if (a.docs.length) {
    h += `<div class="card"><h3>Documents</h3><div class="doclist">` +
      a.docs.map(d => d.exists
        ? `<a href="../../${d.path}">${esc(d.path)}</a>`
        : `<span class="missing">${esc(d.path)} &mdash; allocated but not present</span>`).join('') +
      `</div></div>`;
  }
  if (a.ids.length) h += `<h3 style="font-size:13px;text-transform:uppercase;letter-spacing:.6px;
                            color:var(--muted);margin:18px 0 8px">Records</h3>` + table(a.ids);
  return h;
}

function viewSearch() {
  const total = Object.keys(items).length;
  const n = Object.keys(items).filter(id => matches(items[id])).length;
  return `<h2 class="title">Search results</h2>
    <p class="sub">${n} of ${total} records match &ldquo;${esc(F.q)}&rdquo;
       &middot; <button class="link" onclick="clearSearch()">clear the search</button></p>` +
    table(Object.keys(items));
}
function clearSearch() {
  F.q = '';
  document.getElementById('q').value = '';
  showSearch = false;
  render();
}

// Which of the two wins: typing in the search box shows results, following a link
// shows that record or diagram. Without this, clicking a search result appears to do
// nothing, because the results view would keep overriding it.
let showSearch = false;

function render() {
  const h = location.hash;
  let out;
  if (h.startsWith('#v/')) {
    const g = h.slice(3);
    if (g === 'aspice' || g === 'iso') grouping = g;
  } else if (h.startsWith('#m/')) {
    grouping = 'folder';
  } else if (h.startsWith('#a/')) {
    // Keep the sidebar on the framework the opened area belongs to.
    const a = D.areas.find(x => x.id === decodeURIComponent(h.slice(3)));
    if (a) grouping = a.framework === 'ISO' ? 'iso' : 'aspice';
  }
  if (F.q && showSearch) out = viewSearch();
  else if (h.startsWith('#a/')) out = viewArea(decodeURIComponent(h.slice(3)));
  else if (h.startsWith('#r/')) out = viewRecord(decodeURIComponent(h.slice(3)));
  else if (h.startsWith('#d/')) out = viewDiagram(decodeURIComponent(h.slice(3)));
  else if (h.startsWith('#m/')) out = viewModule(decodeURIComponent(h.slice(3)));
  else if (h === '#all') out = `<h2 class="title">All records</h2>
      <p class="sub">${Object.keys(items).length} records across ${mods.length} modules</p>` +
      table(Object.keys(items));
  else out = viewVModel();
  document.getElementById('content').innerHTML = out;
  document.getElementById('content').scrollTop = 0;
  document.querySelectorAll('th[data-c]').forEach(th => th.onclick = () => {
    const c = th.dataset.c;
    if (sortCol === c) sortAsc = !sortAsc; else { sortCol = c; sortAsc = true; }
    render();
  });
  renderNav();
}

document.getElementById('stats').innerHTML =
  Object.entries(D.stats).map(([k, v]) => `${esc(k)}: <strong>${esc(v)}</strong>`).join(' &middot; ') +
  ` &middot; ${D.ndiagrams} model views &middot; <a href="#v/aspice">V-model</a>
    &middot; <a href="#all">all records</a>`;

document.getElementById('q').oninput = e => {
  F.q = e.target.value.toLowerCase();
  showSearch = true;
  render();
};
for (const [sel, key] of [['fKind','kind'],['fAsil','asil'],['fStatus','status']]) {
  document.getElementById(sel).onchange = e => { F[key] = e.target.value; render(); };
}
document.getElementById('q').addEventListener('keydown', e => {
  if (e.key === 'Escape') clearSearch();
});
window.addEventListener('hashchange', () => { showSearch = false; render(); });
render();
</script>
</body>
</html>
"""


_SVG_PAYLOAD = re.compile(r'"svg":"[A-Za-z0-9+/=]*"')


def normalise(page: str) -> str:
    """Blank the embedded SVG payloads before comparing two versions of the page.

    PlantUML lays text out with the fonts of the machine it runs on, so the same source
    renders to different SVG bytes on macOS and on a CI runner. Those bytes are not
    content: treating them as a change made the page regenerate on every platform switch,
    which produced a commit per push and a false "stale" verdict in --check. A real change
    to a diagram still shows up, because the PlantUML source is embedded next to the SVG
    and is compared normally.
    """
    return _SVG_PAYLOAD.sub('"svg":""', page)


def build_page(root: Path) -> str:
    model = build_model(root)
    data = json.dumps(model, ensure_ascii=False, separators=(",", ":"))
    # Keep the JSON from terminating the surrounding <script> element.
    data = data.replace("</", "<\\/")
    return PAGE.replace("__DATA__", data).replace("__MARKER__", MARKER)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".", help="repository root")
    ap.add_argument("--check", action="store_true", help="check only, exit 1 if stale")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    out = root / OUT_REL

    try:
        page = build_page(root)
    except Exception as exc:  # pragma: no cover - defensive
        print(f"gen_req_browser: {exc}", file=sys.stderr)
        return 2

    current = out.read_text(encoding="utf-8") if out.exists() else None
    unchanged = current is not None and normalise(current) == normalise(page)

    if args.check:
        if not unchanged:
            print(f"Stale: {OUT_REL} - run python3 tools/gen_req_browser.py", file=sys.stderr)
            return 1
        print(f"Up to date: {OUT_REL}")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    if unchanged:
        # Keep the committed rendering rather than rewriting the file with an identical
        # page in a different machine's fonts.
        print(f"Up to date: {OUT_REL}")
        return 0
    out.write_text(page, encoding="utf-8")
    print(f"Written: {OUT_REL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
