#!/usr/bin/env python3
"""Generates a README.md overview for every folder holding Requirements-as-Code records.

Any folder containing at least one Markdown file with YAML front matter and an `id` field gets a
generated README.md with a clickable table of all its records. GitHub renders that file
automatically when the folder is opened.

Uses the same front-matter parser as tools/trace_check.py -- no third-party dependency.

Usage:
    python3 tools/gen_index.py             # write/update the overviews
    python3 tools/gen_index.py --check     # check only, exit 1 if stale
    python3 tools/gen_index.py --root DIR  # different repo root

Exit 0 = up to date or written, 1 = stale (with --check only), 2 = error.

NOTE: produces overviews used for the safety case and is therefore -- like trace_check.py --
a candidate for tool qualification (ISO 26262-8, Clause 11).
See 09_process/plans/tool_qualification.md.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trace_check import parse_front_matter, LIST_FIELDS  # noqa: E402

MARKER = "<!-- generated by tools/gen_index.py -- do not edit manually -->"

SKIP_DIRS = {".git", ".github", ".claude", "node_modules", "__pycache__", "exports"}

# Heading and description per known folder; unknown folders get a default.
TITLES = {
    "01_requirements/customer": (
        "Customer requirements (CR)",
        "Extract of the customer specification, ASPICE SYS.1. The ASIL is determined by the HARA (phase 2).",
    ),
    "01_requirements/system": (
        "System requirements (SYS-REQ)",
        "Derived from CR and FSR, ASPICE SYS.2.",
    ),
    "02_safety/02_hara": (
        "Hazards (H)",
        "Structured form of the HARA rows, ISO 26262-3. Derivation and method in hara.md.",
    ),
    "02_safety/03_fsc": (
        "Safety goals and functional safety concept (SG, FSR)",
        "ISO 26262-3. Safety goals with safe state and FTTI, and the FSR derived from them.",
    ),
    "02_safety/04_tsc": (
        "Technical safety concept (TSR)",
        "ISO 26262-4. Technical safety requirements and their allocation.",
    ),
    "02_safety/05_analyses": (
        "Safety analyses and risks (RISK)",
        "FMEA, FTA, FMEDA, DFA, STPA and the risks tracked.",
    ),
    "05_hardware": (
        "Hardware requirements and safety mechanisms (HW-REQ, SM)",
        "HWE.1-HWE.4, ISO 26262-5.",
    ),
    "06_software": (
        "Software requirements (SW-REQ)",
        "SWE.1-SWE.6, ISO 26262-6.",
    ),
    "07_verification/testcases": (
        "Test cases (TC)",
        "ASPICE SYS.4/SYS.5. Every test case references at least one requirement.",
    ),
}

ID_SPLIT = re.compile(r"^(.*?)-(\d+)$")


def sort_key(rid: str):
    """Sorts CR-2 before CR-10 (numeric rather than lexicographic)."""
    m = ID_SPLIT.match(rid)
    return (m.group(1), int(m.group(2))) if m else (rid, 0)


def short(text: str, limit: int = 130) -> str:
    """Truncates the requirement text for the table column and escapes pipes."""
    t = " ".join(str(text).split()).replace("|", "\\|")
    return t if len(t) <= limit else t[: limit - 1].rstrip() + "…"


def collect(root: Path) -> dict[Path, list[dict]]:
    """Collects all records, grouped by folder."""
    groups: dict[Path, list[dict]] = {}
    for path in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.name == "README.md":
            continue
        try:
            fm = parse_front_matter(path.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not fm or "id" not in fm:
            continue
        for field in LIST_FIELDS:
            val = fm.get(field)
            if val is None:
                fm[field] = []
            elif isinstance(val, str):
                fm[field] = [val] if val.strip() else []
        fm["_name"] = path.name
        groups.setdefault(path.parent, []).append(fm)
    return groups


def render(folder_rel: str, records: list[dict], upstream: dict, downstream: dict) -> str:
    title, desc = TITLES.get(
        folder_rel, (f"Records in `{folder_rel}`", "Automatically generated overview.")
    )
    records = sorted(records, key=lambda r: sort_key(str(r["id"])))

    lines = [
        f"# {title}",
        "",
        MARKER,
        "",
        desc,
        "",
        f"**{len(records)} records.** Click an ID to open the record.",
        "",
        "| ID | Text | Type | ASIL | Status | Upstream | Downstream |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in records:
        rid = str(r["id"])
        up = ", ".join(sorted(upstream.get(rid, []))) or "—"
        dn = ", ".join(sorted(downstream.get(rid, []))) or "—"
        lines.append(
            "| [{id}]({file}) | {text} | {typ} | {asil} | {status} | {up} | {dn} |".format(
                id=rid,
                file=r["_name"],
                text=short(r.get("text", ""), 90),
                typ=r.get("type", "—"),
                asil=r.get("asil", "—"),
                status=r.get("status", "—"),
                up=short(up, 45),
                dn=short(dn, 45),
            )
        )

    # Roll-up by status and ASIL
    def tally(field: str) -> str:
        counts: dict[str, int] = {}
        for r in records:
            counts[str(r.get(field, "—"))] = counts.get(str(r.get(field, "—")), 0) + 1
        return " · ".join(f"{k}: {v}" for k, v in sorted(counts.items()))

    lines += [
        "",
        f"**Status:** {tally('status')}",
        "",
        f"**ASIL:** {tally('asil')}",
        "",
        "---",
        "",
        "**Upstream** is what a record derives from, **downstream** what derives from it, allocates",
        "to it or verifies it. Graphical views of the same links:",
        "[`traceability_views.md`](../../07_verification/reports/traceability_views.md).",
        "",
        "This overview is generated by `tools/gen_index.py` and checked for freshness in CI.",
        "Make changes to the record, not to this file.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".", help="repo root (default: .)")
    ap.add_argument("--check", action="store_true", help="check only, write nothing")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: root not found: {root}", file=sys.stderr)
        return 2

    groups = collect(root)

    # Global link index across all folders: upstream = derives from, downstream = everything
    # that points back at this record by any relation.
    all_recs = {str(r["id"]): r for recs in groups.values() for r in recs}
    upstream: dict[str, set] = {}
    downstream: dict[str, set] = {}
    for rid, rec in all_recs.items():
        for parent in rec["derived_from"]:
            if parent in all_recs:
                upstream.setdefault(rid, set()).add(parent)
                downstream.setdefault(parent, set()).add(rid)
        for field in ("allocated_to", "verified_by"):
            for ref in rec[field]:
                if ref in all_recs:
                    downstream.setdefault(rid, set()).add(ref)
                    upstream.setdefault(ref, set()).add(rid)

    if not groups:
        print("No records found - nothing to do.")
        return 0

    stale: list[str] = []
    written: list[str] = []

    for folder, records in sorted(groups.items()):
        rel = folder.relative_to(root).as_posix()
        target = folder / "README.md"
        content = render(rel, records, upstream, downstream)

        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if MARKER not in existing:
                print(
                    f"WARNING: {rel}/README.md is not generated (no marker) "
                    "- it will not be overwritten.",
                    file=sys.stderr,
                )
                continue
            if existing == content:
                continue

        if args.check:
            stale.append(rel)
        else:
            target.write_text(content, encoding="utf-8")
            written.append(f"{rel}/README.md ({len(records)} records)")

    if args.check:
        if stale:
            print("Stale overviews:")
            for s in stale:
                print(f"  - {s}/README.md")
            print("\nPlease run 'python3 tools/gen_index.py' and commit the result.")
            return 1
        print(f"All overviews up to date ({len(groups)} folders).")
        return 0

    if written:
        print("Updated:")
        for w in written:
            print(f"  - {w}")
    else:
        print(f"All overviews already up to date ({len(groups)} folders).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
